server:
  servlet:
    context-path: /api/v1

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/amigoes
    username: postgres
    password: password
    pool-size: 30
    driverClassName: org.postgresql.Driver



#spring:
#  flyway:
#    url: jdbc:postgresql://localhost:5433/amigoes
#    schemas: amigoes
#    user: postgres
#    password: password
#    baselineOnMigrate: true
